export interface Account {
  id: string;
  name: string;
  type: 'checking' | 'savings' | 'credit' | 'cash';
  color: string;
}

export interface RecurringSchedule {
  type: 'weekly' | 'biweekly' | 'monthly' | 'custom';
  startDate: Date;
  customDays?: number; // For "every X days"
  dayOfMonth?: number; // For monthly (e.g., 1st of month)
  endDate?: Date; // Optional end date for the recurring
}

// Recurring templates are separate from actual transactions
export interface RecurringTemplate {
  id: string;
  type: 'expense' | 'income';
  amount: number;
  category: string;
  description: string;
  accountId?: string;
  schedule: RecurringSchedule;
  isActive: boolean;
}

export interface Transaction {
  id: string;
  type: 'expense' | 'income';
  amount: number;
  category: string;
  description: string;
  date: Date;
  verified: boolean;
  accountId?: string;
  isForecasted?: boolean; // True if this is a future projected transaction
  recurringTemplateId?: string; // Links to the recurring template that generated this
  wasAutoGenerated?: boolean; // True if created from a recurring template
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  color: string;
  budget?: number;
}

export interface MonthlyData {
  month: string;
  year: number;
  income: number;
  expenses: number;
  savings: number;
  isClosed: boolean;
  transactions: Transaction[];
  startingBalance?: number;
}

export interface MonthSettings {
  startingBalance: number;
  accountBalances: Record<string, number>;
}

export const DEFAULT_ACCOUNTS: Account[] = [
  { id: 'checking', name: 'Checking Account', type: 'checking', color: 'hsl(200 85% 45%)' },
  { id: 'savings', name: 'Savings Account', type: 'savings', color: 'hsl(160 65% 40%)' },
  { id: 'credit1', name: 'Credit Card', type: 'credit', color: 'hsl(280 60% 50%)' },
  { id: 'cash', name: 'Cash', type: 'cash', color: 'hsl(38 92% 50%)' },
];

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'housing', name: 'Housing', icon: 'Home', color: 'hsl(175 60% 35%)' },
  { id: 'food', name: 'Food & Dining', icon: 'Utensils', color: 'hsl(38 92% 50%)' },
  { id: 'transport', name: 'Transportation', icon: 'Car', color: 'hsl(200 85% 45%)' },
  { id: 'utilities', name: 'Utilities', icon: 'Zap', color: 'hsl(280 60% 50%)' },
  { id: 'entertainment', name: 'Entertainment', icon: 'Film', color: 'hsl(340 75% 55%)' },
  { id: 'shopping', name: 'Shopping', icon: 'ShoppingBag', color: 'hsl(160 65% 40%)' },
  { id: 'health', name: 'Health', icon: 'Heart', color: 'hsl(0 70% 55%)' },
  { id: 'other', name: 'Other', icon: 'MoreHorizontal', color: 'hsl(220 10% 50%)' },
];
